incountry/sdk-java

.gitignore
.travis.yml
build.gradle
gradle.properties
settings.gradle

This is initial integration with TravisCI

SEC-3 integration with TravisCI

---

src/main/java/com/incountry/Data.java

- [ EN-1306 ]
------------
Target Release
--------------

Removed "null" parameters from toString method of Data object

---

README.md

- [ https://incountry.atlassian.net/browse/EN-1316]
------------
Target Release
--------------
- [-] Please put the target release vehicle this needs to be bundled with.
- [-] Did you increment the version? What is the new version?

Fb en 1316

---

README.md
src/main/java/com/incountry/Data.java

- 
------------
Target Release
--------------

Update latest develop

---

src/main/java/com/incountry/Utils.java
src/main/java/com/incountry/crypto/Crypto.java
src/test/java/com/incountry/crypto/CryptoTest.java

------------
Target Release
--------------

FB_EN-1417 Change from using Hex for encrypted Payloads to Base64

---

.travis.yml

------------
Target Release
--------------

FB_EN-1513 add gradle test to travis

---

src/integration/java/com/incountry/StorageTest.java
src/main/java/com/incountry/BatchData.java
src/main/java/com/incountry/Data.java
src/main/java/com/incountry/FilterRangeParam.java
src/main/java/com/incountry/FilterStringParam.java
src/main/java/com/incountry/FindFilter.java
src/main/java/com/incountry/FindOptions.java
src/main/java/com/incountry/Storage.java

- [EN-1173](https://incountry.atlassian.net/browse/EN-1173)
------------
Target Release
--------------

EN-1173 Add Find method for Java SDK

---

src/integration/java/com/incountry/StorageTest.java
src/main/java/com/incountry/Storage.java
src/main/java/com/incountry/exceptions/StorageClientException.java
src/main/java/com/incountry/exceptions/StorageException.java
src/main/java/com/incountry/exceptions/StorageServerException.java
src/main/java/com/incountry/http/HttpAgent.java
src/main/java/com/incountry/http/IHttpAgent.java
src/test/java/com/incountry/FakeHttpAgent.java
src/test/java/com/incountry/StorageTest.java

- [https://incountry.atlassian.net/browse/EN-1498]
------------
Target Release
--------------

EN-1498: Increase test coverage for Java SDK

---

src/integration/java/com/incountry/StorageTest.java
src/main/java/com/incountry/Storage.java
src/main/java/com/incountry/key_accessor/ISecretKeyAccessor.java
src/main/java/com/incountry/key_accessor/SecretKeyAccessor.java
src/test/java/com/incountry/StorageTest.java

- [https://incountry.atlassian.net/browse/EN-1461]
------------
Target Release
--------------

EN-1461: Java Implementation of SecretKeyAccessor

---

gradle.properties
pom.xml

- [EN-1550](https://incountry.atlassian.net/browse/EN-1550)
------------
Target Release
--------------

EN-1550: Update fasterxml version

---

README.md
src/integration/java/com/incountry/StorageTest.java
src/main/java/com/incountry/Storage.java

- [https://incountry.atlassian.net/browse/EN-1552]
------------
Target Release
--------------

EN-1552: Update Java SDK readme

---

src/main/java/com/incountry/FindFilter.java
src/test/java/com/incountry/FakeHttpAgent.java
src/test/java/com/incountry/StorageTest.java

- [ EN-1555](https://incountry.atlassian.net/browse/EN-1555)
------------
Target Release
--------------

EN-1555: Improve test coverage for Java SDK

---

.gitignore
pom.xml

- https://incountry.atlassian.net/browse/EN-1571
------------
Target Release
--------------

EN-1571 Java SDK Fix version and missing deps

---

src/main/java/com/incountry/Record.java
src/main/java/com/incountry/Storage.java
src/main/java/com/incountry/crypto/ICrypto.java
src/main/java/com/incountry/crypto/impl/Crypto.java
src/main/java/com/incountry/keyaccessor/utils/SecretKeyUtils.java
src/test/java/com/incountry/StorageTest.java
src/test/java/com/incountry/crypto/CryptoTest.java

- https://incountry.atlassian.net/browse/EN-1588
------------
Target Release
--------------

EN-1588 Java SDK should have batchWrite method

---

.gitignore
build.gradle
pom.xml

[FIX] add EN-1571 commit
- https://incountry.atlassian.net/browse/EN-1845
------------
Target Release
--------------

EN-1845 Java SDK Update RC_1.0.0 with EN-1571 

---

src/main/java/com/incountry/Record.java

- https://incountry.atlassian.net/browse/EN-1846
------------
Target Release
--------------

EN-1846 Java SDK RC_1.0.0 read bug

---

src/integration/java/com/incountry/StorageTest.java
src/main/java/com/incountry/BatchRecord.java
src/main/java/com/incountry/FilterStringParam.java
src/main/java/com/incountry/FindFilter.java
src/main/java/com/incountry/FindOptions.java
src/main/java/com/incountry/MigrateResult.java
src/main/java/com/incountry/Record.java
src/main/java/com/incountry/Storage.java
src/main/java/com/incountry/crypto/impl/Crypto.java
src/main/java/com/incountry/exceptions/FindOptionsException.java
src/main/java/com/incountry/keyaccessor/utils/SecretKeyUtils.java
src/test/java/com/incountry/StorageTest.java

- https://incountry.atlassian.net/browse/EN-1591
------------
Target Release
--------------

EN-1591 Java SDK should have migrate method

---

README.md
gradle.properties
pom.xml

[ENH] bump version to 1.0.0
[FIX] minor update to README.md
- https://incountry.atlassian.net/browse/EN-1882
------------
Target Release
--------------

EN-1882 Java SDK Release RC_1.0.0

---

README.md

------------
Target Release
--------------

EN-1902 fix README.md issues

---

LICENSE

[ENH] add MIT license
- https://incountry.atlassian.net/browse/EN-1940
------------
Target Release
--------------

EN-1940 [Java SDK] Add MIT License

---

src/main/java/com/incountry/Record.java
src/main/java/com/incountry/Storage.java
src/main/java/com/incountry/crypto/Crypto.java
src/test/java/com/incountry/StorageTest.java
src/test/java/com/incountry/crypto/CryptoTest.java

- https://incountry.atlassian.net/browse/EN-1778
------------
Target Release
--------------

EN-1778 [Java SDK] Add plaintext (in no-encryption mode) crypto-version support 

---

src/examples/java/com/incounty/FullMIgration.java
src/examples/java/com/incounty/FullMigration.java

- [https://incountry.atlassian.net/browse/EN-1594 ]
------------
Target Release
--------------

EN-1594 Java SDK should provide migration script example

---

README.md

- [https://incountry.atlassian.net/browse/EN-1673 ]
------------
Target Release
--------------

EN-1673 Add migration/key rotation README notes for Java SDK

---

src/integration/java/com/incountry/StorageTest.java
src/main/java/com/incountry/Record.java
src/main/java/com/incountry/Storage.java
src/test/java/com/incountry/StorageTest.java

- https://incountry.atlassian.net/browse/EN-1930
------------
Target Release
--------------

EN-1930 [Java SDK] change batchWrite payload to { "records": records }

---

README.md
gradle.properties

[ENH] bumped version in gradle.properties and README.md
- https://incountry.atlassian.net/browse/EN-2118
------------
Target Release
--------------

EN-2118 [Java SDK] bump RC_1.1.0 version

---

README.md
gradle.properties
src/main/java/com/incountry/BatchRecord.java
src/main/java/com/incountry/FindOptions.java
src/main/java/com/incountry/Record.java
src/main/java/com/incountry/Storage.java
src/main/java/com/incountry/crypto/Crypto.java
src/main/java/com/incountry/crypto/ICrypto.java
src/main/java/com/incountry/exceptions/FindOptionsException.java
src/main/java/com/incountry/exceptions/RecordException.java
src/test/java/com/incountry/StorageTest.java
src/test/java/com/incountry/crypto/CryptoTest.java

- https://incountry.atlassian.net/browse/EN-2121
------------
Target Release
--------------

EN-2121 [Java SDK] Release RC_1.1.0

---

src/main/java/com/incountry/BatchRecord.java
src/main/java/com/incountry/Record.java
src/main/java/com/incountry/Storage.java
src/main/java/com/incountry/crypto/ICrypto.java
src/main/java/com/incountry/crypto/impl/Crypto.java
src/main/java/com/incountry/exceptions/StorageDecryptionException.java
src/test/java/com/incountry/crypto/CryptoTest.java

- https://incountry.atlassian.net/browse/EN-1877
------------
Target Release
--------------

EN-1877 [Java SDK] Drop v0 decryption. Throw an error instead

---

README.md
src/integration/java/com/incountry/StorageTest.java
src/main/java/com/incountry/crypto/CryptoUtils.java
src/main/java/com/incountry/crypto/impl/Crypto.java
src/main/java/com/incountry/keyaccessor/key/SecretKey.java
src/test/java/com/incountry/StorageTest.java

- https://incountry.atlassian.net/browse/EN-1767
------------
Target Release
--------------

EN-1767 [Java SDK] Add ability to provide encryption key directly

---

src/main/java/com/incountry/FilterStringParam.java
src/main/java/com/incountry/FindFilter.java

- https://incountry.atlassian.net/browse/EN-1591
------------
Target Release
--------------

EN-1591 [Java SDK] Java SDK should have migrate method

---

build.gradle
gradle.properties
src/integration/java/com/incountry/residence/sdk/StorageTest.java
src/main/java/com/incountry/residence/sdk/Storage.java
src/main/java/com/incountry/residence/sdk/StorageImpl.java
src/main/java/com/incountry/residence/sdk/tools/JsonUtils.java
src/main/java/com/incountry/residence/sdk/tools/crypto/Crypto.java
src/main/java/com/incountry/residence/sdk/tools/crypto/impl/CryptoImpl.java
src/main/java/com/incountry/residence/sdk/tools/dao/Dao.java
src/main/java/com/incountry/residence/sdk/tools/dao/POP.java
src/main/java/com/incountry/residence/sdk/tools/dao/impl/HttpDaoImpl.java
src/main/java/com/incountry/residence/sdk/tools/http/HttpAgent.java
src/main/java/com/incountry/residence/sdk/tools/http/impl/HttpAgentImpl.java
src/test/java/com/incountry/residence/sdk/FakeHttpAgent.java
src/test/java/com/incountry/residence/sdk/HttpDaoImplTests.java
src/test/java/com/incountry/residence/sdk/RecordTest.java
src/test/java/com/incountry/residence/sdk/StorageSingleTests.java
src/test/java/com/incountry/residence/sdk/crypto/CryptoTest.java
src/test/java/com/incountry/residence/sdk/http/FakeHttpAgent.java
src/test/java/com/incountry/residence/sdk/http/HttpAgentImplTest.java

- https://incountry.atlassian.net/browse/SDK-61
------------
Target Release
--------------

SDK-61 [Java SDK] Refactor to separate Storage and HTTP requests

---

src/integration/java/com/incountry/residence/sdk/StorageTest.java
src/main/java/com/incountry/residence/sdk/Storage.java
src/main/java/com/incountry/residence/sdk/StorageImpl.java
src/main/java/com/incountry/residence/sdk/dto/Record.java
src/main/java/com/incountry/residence/sdk/tools/JsonUtils.java
src/main/java/com/incountry/residence/sdk/tools/dao/impl/HttpDaoImpl.java
src/test/java/com/incountry/residence/sdk/HttpDaoImplTests.java
src/test/java/com/incountry/residence/sdk/RecordTest.java
src/test/java/com/incountry/residence/sdk/StorageSingleTests.java

- https://incountry.atlassian.net/browse/SDK-21
------------
Target Release
--------------

SDK-21 [Java SDK] Don't send country code in JSON body in `write` operation

---

.travis.yml
src/integration/java/com/incountry/residence/sdk/StorageTest.java

- https://incountry.atlassian.net/browse/SDK-59
------------
Target Release
--------------

SDK-59 [Java SDK] Repair running integration tests during PullRequests, demo examples and Java-doc for them

---

src/integration/java/com/incountry/residence/sdk/StorageTest.java
src/main/java/com/incountry/residence/sdk/Storage.java
src/main/java/com/incountry/residence/sdk/StorageImpl.java

- https://incountry.atlassian.net/browse/SDK-45 
------------
Target Release
--------------

SDK-45 [Java SDK] Get rid of Update method

---

README.md
countries.md

- [SDK-65](https://incountry.atlassian.net/browse/SDK-65)
------------
Target Release
--------------

SDK-65 [Java SDK] Add Countries section and a separate countries.md file

---

README.md
countries.md
pull_request_template.md

- [SDK-77](https://incountry.atlassian.net/browse/SDK-77)
------------
Target Release
--------------

SDK-77 [Java SDK] Move countries README.md updates to v1.1.1

---

src/main/java/com/incountry/residence/sdk/tools/dao/impl/HttpDaoImpl.java

- https://incountry.atlassian.net/browse/SDK-89
------------
Target Release
--------------

SDK-89 [Java SDK] Storage cannot initialise with production endpoint

---

README.md
gradle.properties

- [SDK-95](https://incountry.atlassian.net/browse/SDK-95)
------------
Target Release
--------------

SDK-95 [Java SDK] Bump version for RC_1.1.1

---

src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
src/main/java/com/incountry/residence/sdk/StorageImpl.java
src/main/java/com/incountry/residence/sdk/dto/search/FindFilterBuilder.java
src/test/java/com/incountry/residence/sdk/StorageSingleTests.java

- https://incountry.atlassian.net/browse/SDK-86
------------
Target Release
--------------

SDK-86 [Java SDK] FindOne method use incorrect limit value in PopAPI request

---

README.md
countries.md
gradle.properties
pull_request_template.md

- [SDK-92](https://incountry.atlassian.net/browse/SDK-92)
------------
Target Release
--------------

SDK-92 [Java SDK] Release RC_1.1.1

---

README.md
src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
src/main/java/com/incountry/residence/sdk/Storage.java
src/main/java/com/incountry/residence/sdk/StorageImpl.java
src/main/java/com/incountry/residence/sdk/dto/search/FilterNumberParam.java
src/main/java/com/incountry/residence/sdk/dto/search/FilterStringParam.java
src/main/java/com/incountry/residence/sdk/dto/search/FindFilter.java
src/main/java/com/incountry/residence/sdk/dto/search/FindFilterBuilder.java
src/main/java/com/incountry/residence/sdk/tools/JsonUtils.java
src/main/java/com/incountry/residence/sdk/tools/crypto/Crypto.java
src/main/java/com/incountry/residence/sdk/tools/crypto/impl/CryptoImpl.java
src/main/java/com/incountry/residence/sdk/tools/dao/Dao.java
src/main/java/com/incountry/residence/sdk/tools/dao/impl/HttpDaoImpl.java
src/main/java/com/incountry/residence/sdk/tools/exceptions/StorageClientException.java
src/main/java/com/incountry/residence/sdk/tools/keyaccessor/SecretKeyAccessor.java
src/main/java/com/incountry/residence/sdk/tools/keyaccessor/impl/SecretKeyAccessorImpl.java
src/main/java/com/incountry/residence/sdk/tools/keyaccessor/key/SecretKey.java
src/main/java/com/incountry/residence/sdk/tools/keyaccessor/key/SecretsData.java
src/test/java/com/incountry/residence/sdk/FilterNumberParamTest.java
src/test/java/com/incountry/residence/sdk/FilterStringParamTest.java
src/test/java/com/incountry/residence/sdk/FindFilterBuilderIsolatedTest.java
src/test/java/com/incountry/residence/sdk/FindFilterTest.java
src/test/java/com/incountry/residence/sdk/HttpDaoImplTests.java
src/test/java/com/incountry/residence/sdk/JsonUtilsTest.java
src/test/java/com/incountry/residence/sdk/RecordTest.java
src/test/java/com/incountry/residence/sdk/StorageSingleTests.java
src/test/java/com/incountry/residence/sdk/crypto/CryptoTest.java
src/test/java/com/incountry/residence/sdk/keyaccessor/SecretsDataUtilsTest.java

https://incountry.atlassian.net/browse/SDK-79
------------
Target Release
--------------

SDK-79 [Java SDK] Add StorageClientException

---

README.md
src/main/java/com/incountry/residence/sdk/tools/dao/impl/HttpDaoImpl.java
src/test/java/com/incountry/residence/sdk/HttpDaoImplTests.java
src/test/java/com/incountry/residence/sdk/http/FakeHttpAgent.java

- https://incountry.atlassian.net/browse/SDK-89
------------
Target Release
--------------

SDK-89 [Java SDK] Storage cannot initialise with production endpoint - test improving

---

build.gradle
config/spotbugs/exclude.xml
src/main/java/com/incountry/residence/sdk/tools/JsonUtils.java
src/main/java/com/incountry/residence/sdk/tools/crypto/impl/CryptoImpl.java
src/main/java/com/incountry/residence/sdk/tools/dao/impl/ApiResponse.java
src/main/java/com/incountry/residence/sdk/tools/dao/impl/HttpDaoImpl.java
src/main/java/com/incountry/residence/sdk/tools/exceptions/RecordException.java
src/main/java/com/incountry/residence/sdk/tools/http/HttpAgent.java
src/main/java/com/incountry/residence/sdk/tools/http/impl/HttpAgentImpl.java
src/test/java/com/incountry/residence/sdk/HttpDaoImplTests.java
src/test/java/com/incountry/residence/sdk/RecordTest.java
src/test/java/com/incountry/residence/sdk/StorageSingleTests.java
src/test/java/com/incountry/residence/sdk/http/FakeHttpAgent.java
src/test/java/com/incountry/residence/sdk/http/HttpAgentImplTest.java

- [SDK-37](https://incountry.atlassian.net/browse/SDK-37)
------------
Target Release
--------------

SDK-37 [Java SDK] Validate PoPAPI response

---

README.md
src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
src/main/java/com/incountry/residence/sdk/dto/search/FilterNumberParam.java
src/main/java/com/incountry/residence/sdk/dto/search/FilterStringParam.java
src/main/java/com/incountry/residence/sdk/dto/search/FindFilter.java
src/main/java/com/incountry/residence/sdk/dto/search/FindFilterBuilder.java
src/main/java/com/incountry/residence/sdk/tools/JsonUtils.java
src/main/java/com/incountry/residence/sdk/tools/dao/impl/ApiResponse.java
src/test/java/com/incountry/residence/sdk/FilterStringParamTest.java
src/test/java/com/incountry/residence/sdk/FindFilterBuilderIsolatedTest.java
src/test/java/com/incountry/residence/sdk/FindFilterTest.java

- [SDK-96](https://incountry.atlassian.net/browse/SDK-96)
------------
Target Release
--------------

SDK-96 [Java SDK] SDK contains unsupported filters for range_key

---

README.md

- [SDK-22](https://incountry.atlassian.net/browse/SDK-22)
------------
Target Release
--------------

SDK-22 [Java SDK] Provide minimum JVM specs

---

src/main/java/com/incountry/residence/sdk/StorageImpl.java
src/test/java/com/incountry/residence/sdk/HttpDaoImplTests.java
src/test/java/com/incountry/residence/sdk/StorageSingleTests.java

- [SDK-101](https://incountry.atlassian.net/browse/SDK-101)
------------
Target Release
--------------

SDK-101 [ Java SDK] Method BatchWrite doesn't throw exception in negative cases

---

src/main/java/com/incountry/residence/sdk/StorageImpl.java
src/main/java/com/incountry/residence/sdk/tools/crypto/impl/CryptoImpl.java
src/test/java/com/incountry/residence/sdk/crypto/CryptoTest.java

- [SDK-97](https://incountry.atlassian.net/browse/SDK-97)
------------
Target Release
--------------

SDK-97 [Java SDK] Refactor SecretKeyAccessor

---

build.gradle
src/main/java/com/incountry/residence/sdk/tools/JsonUtils.java
src/test/java/com/incountry/residence/sdk/HttpDaoImplTests.java
src/test/java/com/incountry/residence/sdk/RecordTest.java
src/test/java/com/incountry/residence/sdk/StorageSingleTests.java

- [SDK-115](https://incountry.atlassian.net/browse/SDK-115)
------------
Target Release
--------------

SDK-115 [Java SDK] User can't read record that was written by NodeJS SDK

---

src/main/java/com/incountry/residence/sdk/tools/JsonUtils.java
src/test/java/com/incountry/residence/sdk/RecordTest.java
src/test/java/com/incountry/residence/sdk/crypto/AllSdkEncryptionTest.java

- [SDK-118](https://incountry.atlassian.net/browse/SDK-118)
------------
Target Release
--------------

SDK-118 [Jave SDK] Add universal unit tests for encrypt/decrypt payload methods, branch RC_2.0.0 

---

src/main/java/com/incountry/residence/sdk/tools/dao/impl/HttpDaoImpl.java
src/test/java/com/incountry/residence/sdk/HttpDaoImplTests.java

- [SDK-122](https://incountry.atlassian.net/browse/SDK-122)
------------
Target Release
--------------

SDK-122 [Java SDK] Postpone PoPAPI response validation for 2.0.0 release

---

src/main/java/com/incountry/residence/sdk/tools/dao/impl/HttpDaoImpl.java
src/test/java/com/incountry/residence/sdk/HttpDaoImplTests.java

- [SDK-122](https://incountry.atlassian.net/browse/SDK-122)
------------
Target Release
--------------

SDK-122 [Java SDK] Postpone PoPAPI response validation for 2.0.0 release, branch 'develop'

---

src/main/java/com/incountry/residence/sdk/tools/dao/Dao.java
src/main/java/com/incountry/residence/sdk/tools/dao/impl/HttpDaoImpl.java
src/test/java/com/incountry/residence/sdk/HttpDaoImplTests.java

- [SDK-126](https://incountry.atlassian.net/browse/SDK-126)
------------
Target Release
--------------

SDK-126 [Java SDK] Use default endPoint when country is not in country list, branch RC_2.0.0

---

src/main/java/com/incountry/residence/sdk/tools/dao/Dao.java
src/main/java/com/incountry/residence/sdk/tools/dao/impl/HttpDaoImpl.java
src/test/java/com/incountry/residence/sdk/HttpDaoImplTests.java

- [SDK-126](https://incountry.atlassian.net/browse/SDK-126)
------------
Target Release
--------------

SDK-126 [Java SDK] Use default endPoint when country is not in country list, branch 'DEVELOP'

---

README.md
src/integration/java/com/incountry/residence/sdk/OAuthTest.java
src/main/java/com/incountry/residence/sdk/StorageConfig.java
src/main/java/com/incountry/residence/sdk/StorageImpl.java
src/main/java/com/incountry/residence/sdk/tools/dao/impl/HttpDaoImpl.java
src/main/java/com/incountry/residence/sdk/tools/http/impl/HttpAgentImpl.java
src/main/java/com/incountry/residence/sdk/tools/http/impl/OAuthTokenClient.java
src/test/java/com/incountry/residence/sdk/StorageTest.java
src/test/java/com/incountry/residence/sdk/http/AuthTest.java
src/test/java/com/incountry/residence/sdk/http/HttpAgentImplTest.java
src/test/java/com/incountry/residence/sdk/http/mocks/FakeHttpServer.java

- [SDK-125](https://incountry.atlassian.net/browse/SDK-125)
------------
Target Release
--------------

SDK-125 [Java SDK] Add HTTP timeout configuration

---

src/main/java/com/incountry/residence/sdk/tools/http/impl/HttpAgentImpl.java
src/test/java/com/incountry/residence/sdk/http/HttpAgentImplTest.java
src/test/java/com/incountry/residence/sdk/http/mocks/FakeHttpServer.java

- [SDK-128](https://incountry.atlassian.net/browse/SDK-128)
------------
Target Release
--------------

SDK-128 [Java SDK] NPE when PoP API fails, branch RC_2.0.0

---

src/main/java/com/incountry/residence/sdk/tools/http/impl/HttpAgentImpl.java
src/test/java/com/incountry/residence/sdk/http/HttpAgentImplTest.java

- [SDK-128](https://incountry.atlassian.net/browse/SDK-128)
------------
Target Release
--------------

SDK-128 [Java SDK] NPE when PoP API fails, branch 'develop'

---

build.gradle

- [SDK-129](https://incountry.atlassian.net/browse/SDK-129)
------------
Target Release
--------------

SDK-129 [Java SDK] Incorrect scope of GSON, branch 'RC_2.0.0'

---

build.gradle

- [SDK-129](https://incountry.atlassian.net/browse/SDK-129)
------------
Target Release
--------------

SDK-129 [Java SDK] Incorrect scope of GSON, branch 'develop'

---

README.md
pull_request_template.md

- [SDK-136](https://incountry.atlassian.net/browse/SDK-136)
------------
Target Release
--------------

SDK-136 [Java SDK] Fix typo in README, add SonarCloud badges, branch RC_2.0.0

---

README.md

- [SDK-136](https://incountry.atlassian.net/browse/SDK-136)
------------
Target Release
--------------

SDK-136 [Java SDK] Fix typo in README, add SonarCloud badges, branch 'develop'

---

src/main/java/com/incountry/residence/sdk/StorageImpl.java
src/test/java/com/incountry/residence/sdk/StorageTest.java

- [SDK-142](https://incountry.atlassian.net/browse/SDK-142)
------------
Target Release
--------------

SDK-142 [Java SDK] Negative cases with null country value return incorrect error message, branch DEVELOP

---

.travis.yml
README.md
src/integration/java/com/incountry/residence/sdk/OAuthTest.java
src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
src/main/java/com/incountry/residence/sdk/StorageConfig.java
src/main/java/com/incountry/residence/sdk/StorageImpl.java
src/main/java/com/incountry/residence/sdk/tools/dao/impl/HttpDaoImpl.java
src/main/java/com/incountry/residence/sdk/tools/http/HttpAgent.java
src/main/java/com/incountry/residence/sdk/tools/http/TokenClient.java
src/main/java/com/incountry/residence/sdk/tools/http/impl/ApiKeyTokenClient.java
src/main/java/com/incountry/residence/sdk/tools/http/impl/HttpAgentImpl.java
src/main/java/com/incountry/residence/sdk/tools/http/impl/OAuthTokenClient.java
src/test/java/com/incountry/residence/sdk/HttpDaoImplTests.java
src/test/java/com/incountry/residence/sdk/ProxyUtilsTest.java
src/test/java/com/incountry/residence/sdk/StorageTest.java
src/test/java/com/incountry/residence/sdk/http/AuthTest.java
src/test/java/com/incountry/residence/sdk/http/HttpAgentImplTest.java
src/test/java/com/incountry/residence/sdk/http/mocks/FakeHttpAgent.java

- [SDK-139](https://incountry.atlassian.net/browse/SDK-139)
------------
Target Release
--------------

SDK-139 [Java SDK] add ability to provide endpoint mask (and update minipop token acquisition)

---

src/main/java/com/incountry/residence/sdk/tools/http/impl/OAuthTokenClient.java

- [SDK-139](https://incountry.atlassian.net/browse/SDK-139)
------------
Target Release
--------------

SDK-139 [Java SDK] add ability to provide endpoint mask (and update minipop token acquisition) - production endpoint

---

src/main/java/com/incountry/residence/sdk/StorageImpl.java
src/test/java/com/incountry/residence/sdk/StorageSingleTests.java

- [SDK-142](https://incountry.atlassian.net/browse/SDK-142)
------------
Target Release
--------------

SDK-142 [Java SDK] Negative cases with null country value return incorrect error message, branch RC_2.0.0

---

README.md

- [SDK-146](https://incountry.atlassian.net/browse/SDK-146)
------------
Target Release
--------------

SDK-146 [Java SDK] Update README's example values - branch RC_2.0.0

---

README.md

- [SDK-146](https://incountry.atlassian.net/browse/SDK-146)
------------
Target Release
--------------

SDK-146 [Java SDK] Update README's example values - branch 'develop'

---

config/spotbugs/exclude.xml
src/main/java/com/incountry/residence/sdk/StorageImpl.java
src/main/java/com/incountry/residence/sdk/tools/JsonUtils.java
src/main/java/com/incountry/residence/sdk/tools/transfer/TransferBatch.java
src/main/java/com/incountry/residence/sdk/tools/transfer/TransferPop.java
src/main/java/com/incountry/residence/sdk/tools/transfer/TransferPopList.java
src/main/java/com/incountry/residence/sdk/tools/transfer/TransferRecord.java
src/test/java/com/incountry/residence/sdk/HttpDaoImplTests.java
src/test/java/com/incountry/residence/sdk/JsonUtilsTest.java
src/test/java/com/incountry/residence/sdk/StorageTest.java
src/test/java/com/incountry/residence/sdk/TransferBatchTest.java
src/test/java/com/incountry/residence/sdk/TransferRecordTest.java
src/test/java/com/incountry/residence/sdk/crypto/CryptoManagerTest.java
src/test/java/com/incountry/residence/sdk/crypto/CustomCryptoTest.java
src/test/java/com/incountry/residence/sdk/http/AuthTest.java
src/test/java/com/incountry/residence/sdk/http/HttpAgentImplTest.java
src/test/java/com/incountry/residence/sdk/keyaccessor/SecretsTest.java
src/test/java/com/incountry/residence/sdk/search/FilterNumberParamTest.java
src/test/java/com/incountry/residence/sdk/search/FindFilterBuilderIsolatedTest.java
src/test/java/com/incountry/residence/sdk/search/FindFilterTest.java

- [SDK-133](https://incountry.atlassian.net/browse/SDK-133)
------------
Target Release
--------------

SDK-133 [Java SDK] Improve test quality

---

.travis.yml
gradle.properties

------------
Target Release
--------------

SDK-154 [Java SDK] Release RC_2.0.0 - resolve conflicts with branch 'master'

---

src/test/java/com/incountry/residence/sdk/FilterNumberParamTest.java
src/test/java/com/incountry/residence/sdk/FilterStringParamTest.java
src/test/java/com/incountry/residence/sdk/FindFilterBuilderIsolatedTest.java
src/test/java/com/incountry/residence/sdk/FindFilterTest.java
src/test/java/com/incountry/residence/sdk/JsonUtilsTest.java
src/test/java/com/incountry/residence/sdk/crypto/CryptoTest.java
src/test/java/com/incountry/residence/sdk/keyaccessor/SecretsDataGeneratorTest.java

------------
Target Release
--------------

SDK-154 [Java SDK] Release RC_2.0.0 - fix sonar alerts

---

.travis.yml
gradle/wrapper/gradle-wrapper.properties

------------
Target Release
--------------

SDK-154 [Java SDK] Release RC_2.0.0 - change gradle version for sonar test coverage metric

---

.travis.yml
build.gradle
gradle.properties

------------
Target Release
--------------

SDK-154 [Java SDK] Release RC_2.0.0 - change jacoco config for sonar test coverage metric

---

build.gradle

------------
Target Release
--------------

SDK-154 [Java SDK] Release RC_2.0.0 - change developer id

---

README.md

------------
Target Release
--------------

SDK-169 [Java SDK] Release RC_2.1.0 - fix README.md

---

src/test/java/com/incountry/residence/sdk/crypto/CryptoManagerTest.java

------------
Target Release
--------------

SDK-169 [Java SDK] Release RC_2.1.0 - fix issues from sonar

---

README.md
src/integration/java/com/incountry/residence/sdk/OAuthTest.java
src/main/java/com/incountry/residence/sdk/StorageConfig.java
src/main/java/com/incountry/residence/sdk/StorageImpl.java
src/main/java/com/incountry/residence/sdk/tools/http/impl/OAuthTokenClient.java
src/test/java/com/incountry/residence/sdk/ParamsFromEnvTest.java
src/test/java/com/incountry/residence/sdk/StorageConfigTest.java
src/test/java/com/incountry/residence/sdk/http/TokenClientTest.java

- [SDK-172](https://incountry.atlassian.net/browse/SDK-172)
------------
Target Release
--------------

SDK-172 [Java SDK] add authEndpoints StorageConfig option

---

README.md
gradle.properties
src/integration/java/com/incountry/residence/sdk/OAuthTest.java
src/main/java/com/incountry/residence/sdk/StorageConfig.java
src/main/java/com/incountry/residence/sdk/StorageImpl.java
src/main/java/com/incountry/residence/sdk/tools/http/impl/OAuthTokenClient.java
src/test/java/com/incountry/residence/sdk/ParamsFromEnvTest.java
src/test/java/com/incountry/residence/sdk/StorageConfigTest.java
src/test/java/com/incountry/residence/sdk/crypto/CryptoManagerTest.java
src/test/java/com/incountry/residence/sdk/http/TokenClientTest.java

------------
Target Release
--------------

SDK-169 [Java SDK] Release RC_2.1.0 - add changes from develop

---

README.md

------------
Target Release
--------------

SDK-169 [Java SDK] Release RC_2.1.0 - fix typo in README.md

---

src/main/java/com/incountry/residence/sdk/tools/http/impl/OAuthTokenClient.java

- [SDK-176](https://incountry.atlassian.net/browse/SDK-176)
------------
Target Release
--------------

SDK-176 [Java SDK] log OAuth server url at TRACE log level

---

src/test/java/com/incountry/residence/sdk/TransferRecordTest.java
src/test/java/com/incountry/residence/sdk/crypto/CustomCryptoTest.java

------------
Target Release
--------------

SDK-169 [Java SDK] Release RC_2.1.0 - fix new sonar issues from master branch

---

README.md
src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
src/main/java/com/incountry/residence/sdk/dto/Record.java
src/main/java/com/incountry/residence/sdk/dto/search/FilterNumberParam.java
src/main/java/com/incountry/residence/sdk/dto/search/FindFilterBuilder.java
src/main/java/com/incountry/residence/sdk/tools/JsonUtils.java
src/test/java/com/incountry/residence/sdk/HttpDaoImplTests.java
src/test/java/com/incountry/residence/sdk/RecordTest.java
src/test/java/com/incountry/residence/sdk/StorageTest.java
src/test/java/com/incountry/residence/sdk/TransferRecordTest.java
src/test/java/com/incountry/residence/sdk/crypto/AllSdkEncryptionTest.java
src/test/java/com/incountry/residence/sdk/search/FilterNumberParamTest.java
src/test/java/com/incountry/residence/sdk/search/FindFilterBuilderIsolatedTest.java

- [SDK-177](https://incountry.atlassian.net/browse/SDK-177)
------------
Target Release
--------------

SDK-177 [JavaSDK] Method find cannot parse range_key with long int on PROD

---

README.md

------------
Target Release
--------------

SDK-169 [Java SDK] Release RC_2.1.0 - readme update

---

.travis.yml
src/main/java/com/incountry/residence/sdk/StorageImpl.java

- [SDK-178](https://incountry.atlassian.net/browse/SDK-178)
------------
Target Release
--------------

SDK-178 [Java SDK] Get actual test coverage during PR to any branch

---

README.md

- [SDK-179](https://incountry.atlassian.net/browse/SDK-179)
------------
Target Release
--------------

SDK-179 [Java SDK] Add badges to README

---

.travis.yml

- [SDK-158](https://incountry.atlassian.net/browse/SDK-158)
------------
Target Release
--------------

SDK-158 [Java SDK] optimize PR execution

---

.travis.yml

- [SDK-193](https://incountry.atlassian.net/browse/SDK-193)
------------
Target Release
--------------

SDK-193 [Java SDK] Get rid of double Sonar code scanning

---

README.md
src/main/java/com/incountry/residence/sdk/StorageConfig.java
src/main/java/com/incountry/residence/sdk/StorageImpl.java

- [SDK-209](https://incountry.atlassian.net/browse/SDK-209)
------------
Target Release
--------------

SDK-209 [Java SDK] Update README to mention Schema 2.2 changes

---

.travis.yml
src/main/java/com/incountry/residence/sdk/tools/JsonUtils.java
src/test/java/com/incountry/residence/sdk/HttpDaoImplTests.java
src/test/java/com/incountry/residence/sdk/JsonUtilsTest.java
src/test/java/com/incountry/residence/sdk/http/TokenClientTest.java
src/test/java/com/incountry/residence/sdk/search/FilterNumberParamTest.java
src/test/java/com/incountry/residence/sdk/search/FilterStringParamTest.java

- [SDK-159](https://incountry.atlassian.net/browse/SDK-159)
------------
Target Release
--------------

SDK-159 [Java SDK] Increase test coverage up to 99%

---

src/main/java/com/incountry/residence/sdk/StorageImpl.java
src/main/java/com/incountry/residence/sdk/dto/MigrateResult.java
src/test/java/com/incountry/residence/sdk/StorageTest.java

- [SDK-219](https://incountry.atlassian.net/browse/SDK-219)
------------
Target Release
--------------

SDK-219 [Java SDK] Fix bug at 'Migration' method

---

README.md

- [SDK-215](https://incountry.atlassian.net/browse/SDK-215)
------------
Target Release
--------------

SDK-215 [Java SDK] Release v3.0.0 - README updates

---

build.gradle
src/main/java/com/incountry/residence/sdk/dto/MigrateResult.java
src/test/java/com/incountry/residence/sdk/StorageTest.java

- [SDK-219](https://incountry.atlassian.net/browse/SDK-219)
------------
Target Release
--------------

SDK-219 [Java SDK] Fix bug at 'Migration' method, add getter for errors in MigrateResult, run unit tests parallel

---

gradle.properties
src/integration/java/com/incountry/residence/sdk/OAuthTest.java
src/main/java/com/incountry/residence/sdk/StorageImpl.java
src/test/java/com/incountry/residence/sdk/http/HttpAgentImplTest.java
src/test/java/com/incountry/residence/sdk/http/TokenClientTest.java

- [SDK-235](https://incountry.atlassian.net/browse/SDK-235)
------------
Target Release
--------------

SDK-235 [Java SDK] Update Apache HttpClient to 4.5.13

---

README.md
build.gradle
config/spotbugs/exclude.xml
src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
src/main/java/com/incountry/residence/sdk/StorageImpl.java
src/main/java/com/incountry/residence/sdk/tools/JsonUtils.java
src/main/java/com/incountry/residence/sdk/tools/crypto/CryptoUtils.java
src/main/java/com/incountry/residence/sdk/tools/crypto/DefaultCrypto.java
src/main/java/com/incountry/residence/sdk/tools/dao/impl/HttpDaoImpl.java
src/main/java/com/incountry/residence/sdk/tools/keyaccessor/key/SecretKey.java
src/main/java/com/incountry/residence/sdk/tools/keyaccessor/key/SecretsData.java
src/main/java/com/incountry/residence/sdk/tools/keyaccessor/key/SecretsDataGenerator.java
src/test/java/com/incountry/residence/sdk/HttpDaoImplTests.java
src/test/java/com/incountry/residence/sdk/JsonUtilsTest.java
src/test/java/com/incountry/residence/sdk/StorageTest.java
src/test/java/com/incountry/residence/sdk/TransferBatchTest.java
src/test/java/com/incountry/residence/sdk/TransferRecordTest.java
src/test/java/com/incountry/residence/sdk/crypto/CryptoManagerTest.java
src/test/java/com/incountry/residence/sdk/crypto/CustomCryptoTest.java
src/test/java/com/incountry/residence/sdk/crypto/testimpl/CryptoStub.java
src/test/java/com/incountry/residence/sdk/keyaccessor/SecretsTest.java
travis-build.sh

- [SDK-239](https://incountry.atlassian.net/browse/SDK-239)
------------
Target Release
--------------

SDK-239 [Java SDK] Fix security requirements

---

config/spotbugs/exclude.xml
src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java

- [SDK-241](https://incountry.atlassian.net/browse/SDK-241)
------------
Target Release
--------------

SDK-241 [Java SDK] Improve integration tests

---

.travis.yml
build.gradle
gradle.properties

- [SDK-224](https://incountry.atlassian.net/browse/SDK-224)
------------
Target Release
--------------

SDK-224 [Java SDK] Remove dependency check from java-sdk

---

src/main/java/com/incountry/residence/sdk/tools/keyaccessor/key/SecretKey.java
src/main/java/com/incountry/residence/sdk/tools/keyaccessor/key/SecretsDataGenerator.java
src/test/java/com/incountry/residence/sdk/keyaccessor/SecretsTest.java

- [SDK-247](https://incountry.atlassian.net/browse/SDK-247)
------------
Target Release
--------------

SDK-247 [Java SDK] SDK should accept base64 encoded keys in SecretsData instead of utf-8 encoded

---

src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
src/main/java/com/incountry/residence/sdk/dto/search/FindFilterBuilder.java
src/test/java/com/incountry/residence/sdk/JsonUtilsTest.java
src/test/java/com/incountry/residence/sdk/StorageTest.java

- [SDK-237](https://incountry.atlassian.net/browse/SDK-237)
------------
Target Release
--------------

SDK-237 [Java SDK] Add search_keys filter support

---

src/main/java/com/incountry/residence/sdk/dto/Record.java
src/main/java/com/incountry/residence/sdk/tools/JsonUtils.java
src/main/java/com/incountry/residence/sdk/tools/transfer/TransferRecord.java
src/test/java/com/incountry/residence/sdk/RecordTest.java
src/test/java/com/incountry/residence/sdk/StorageTest.java
src/test/java/com/incountry/residence/sdk/crypto/AllSdkEncryptionTest.java

- [SDK-280](https://incountry.atlassian.net/browse/SDK-280)
------------
Target Release
--------------

SDK-280 [Java SDK] Refactor JSON serialisation for Record

---

README.md
src/main/java/com/incountry/residence/sdk/tools/keyaccessor/key/SecretKey.java
src/main/java/com/incountry/residence/sdk/tools/keyaccessor/key/SecretsDataGenerator.java
src/test/java/com/incountry/residence/sdk/keyaccessor/SecretsTest.java

- [SDK-247](https://incountry.atlassian.net/browse/SDK-247)
------------
Target Release
--------------

SDK-247 [Java SDK] SDK should accept base64 encoded keys in SecretsData instead of utf-8 encoded - change error messages

---

README.md
src/main/java/com/incountry/residence/sdk/tools/keyaccessor/key/SecretKey.java

- [SDK-247](https://incountry.atlassian.net/browse/SDK-247)
------------
Target Release
--------------

SDK-247 [Java SDK] SDK should accept base64 encoded keys in SecretsData instead of utf-8 encoded - update README#2

---

.travis.yml

- [SDK-300](https://incountry.atlassian.net/browse/SDK-300)
------------
Target Release
--------------

SDK-300 [Java SDK] Release v3.3.0 - add Node.js version for travis env

---

config/spotbugs/exclude.xml
src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
src/main/java/com/incountry/residence/sdk/tools/containers/ApiResponse.java
src/main/java/com/incountry/residence/sdk/tools/dao/impl/HttpDaoImpl.java
src/main/java/com/incountry/residence/sdk/tools/http/impl/HttpAgentImpl.java
src/test/java/com/incountry/residence/sdk/HttpDaoImplTests.java
src/test/java/com/incountry/residence/sdk/StorageTest.java
src/test/java/com/incountry/residence/sdk/http/HttpAgentImplTest.java
src/test/java/com/incountry/residence/sdk/http/mocks/FakeHttpAgent.java

- [SDK-318](https://incountry.atlassian.net/browse/SDK-318)
------------
Target Release
--------------

SDK-318 [Java SDK] User can't get binary attached file

---

.travis.yml

- [SDK-300](https://incountry.atlassian.net/browse/SDK-300)
------------
Target Release
--------------

SDK-300 [Java SDK] Release v3.3.0 - change Travis config for SNYK scanner

---

.travis.yml

- [SDK-300](https://incountry.atlassian.net/browse/SDK-300)
------------
Target Release
--------------

SDK-300 [Java SDK] Release v3.3.0 - change travis config for Snyk

---

README.md
build.gradle
gradle.properties
src/integration/java/com/incountry/residence/sdk/AwsKmsExample.java
src/integration/java/com/incountry/residence/sdk/FullMigrationExample.java

- [SDK-253](https://incountry.atlassian.net/browse/SDK-253)
------------
Target Release
--------------

SDK-253 [Java SDK] AWS KMS Key integration example

---

README.md

- [SDK-329](https://incountry.atlassian.net/browse/SDK-329)
------------
Target Release
--------------

SDK-329 [Java SDK] update README with crypto refactor changes

---

README.md
config/spotbugs/exclude.xml
src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
src/main/java/com/incountry/residence/sdk/dto/Record.java
src/main/java/com/incountry/residence/sdk/dto/search/DateField.java
src/main/java/com/incountry/residence/sdk/dto/search/FindFilter.java
src/main/java/com/incountry/residence/sdk/dto/search/SortField.java
src/main/java/com/incountry/residence/sdk/dto/search/StringField.java
src/main/java/com/incountry/residence/sdk/dto/search/internal/DateFilter.java
src/main/java/com/incountry/residence/sdk/tools/DtoTransformer.java
src/main/java/com/incountry/residence/sdk/tools/dao/impl/HttpDaoImpl.java
src/test/java/com/incountry/residence/sdk/FindResultTest.java
src/test/java/com/incountry/residence/sdk/RecordTest.java
src/test/java/com/incountry/residence/sdk/search/FindFilterTest.java

- [SDK-308](https://incountry.atlassian.net/browse/SDK-308)
------------
Target Release
--------------

SDK-308 [Java SDK] add Schema 2.4 support

---

README.md
src/integration/java/com/incountry/residence/sdk/OAuthTest.java
src/main/java/com/incountry/residence/sdk/StorageConfig.java
src/main/java/com/incountry/residence/sdk/StorageImpl.java
src/main/java/com/incountry/residence/sdk/oauth/OauthTokenAccessor.java
src/main/java/com/incountry/residence/sdk/tools/http/TokenClient.java
src/main/java/com/incountry/residence/sdk/tools/http/impl/ApiKeyTokenClient.java
src/main/java/com/incountry/residence/sdk/tools/http/impl/HttpAgentImpl.java
src/main/java/com/incountry/residence/sdk/tools/http/impl/OAuthTokenClient.java
src/test/java/com/incountry/residence/sdk/StorageConfigTest.java
src/test/java/com/incountry/residence/sdk/StorageTest.java
src/test/java/com/incountry/residence/sdk/http/TokenClientTest.java

- [SDK-304](https://incountry.atlassian.net/browse/SDK-304)
------------
Target Release
--------------

SDK-304 [Java SDK] Allow oAuth2 token Storage initialization

---

src/integration/java/com/incountry/residence/sdk/CredentialsHelper.java
src/integration/java/com/incountry/residence/sdk/OAuthTest.java
src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
src/main/java/com/incountry/residence/sdk/StorageImpl.java
src/main/java/com/incountry/residence/sdk/tools/http/impl/AbstractHttpRequestCreator.java
src/test/java/com/incountry/residence/sdk/StorageTest.java
src/test/java/com/incountry/residence/sdk/http/mocks/FakeHttpServer.java

- [SDK-353](https://incountry.atlassian.net/browse/SDK-353)
------------
Target Release
--------------

SDK-353 [Java SDK] SDK sends wrong content-length, incompatible with file upload for POPAPI v.2.14 and higher

---

src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
src/main/java/com/incountry/residence/sdk/tools/http/impl/AbstractHttpRequestCreator.java
src/test/java/com/incountry/residence/sdk/crypto/CustomCryptoTest.java

- [SDK-353](https://incountry.atlassian.net/browse/SDK-353)
------------
Target Release
--------------

SDK-353 [Java SDK] SDK sends wrong content-length, incompatible with file upload for POPAPI v.2.14 and higher - fix encoding for file uploading

---

src/main/java/com/incountry/residence/sdk/crypto/SecretsDataGenerator.java
src/test/java/com/incountry/residence/sdk/crypto/SecretsTest.java

- [SDK-361](https://incountry.atlassian.net/browse/SDK-361)
------------
Target Release
--------------

SDK-361 [Java SDK] Not clear error message when the user sends an empty string as secret data

---

src/main/java/com/incountry/residence/sdk/StorageImpl.java
src/main/java/com/incountry/residence/sdk/tools/DtoTransformer.java
src/test/java/com/incountry/residence/sdk/StorageTest.java

- [SDK-362](https://incountry.atlassian.net/browse/SDK-362)
------------
Target Release
--------------

SDK-362 [Java SDK] SDK doesn't accept empty filter

---

README.md
gradle.properties
src/integration/java/com/incountry/residence/sdk/CredentialsHelper.java
src/integration/java/com/incountry/residence/sdk/OAuthTest.java
src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
src/main/java/com/incountry/residence/sdk/StorageImpl.java
src/main/java/com/incountry/residence/sdk/tools/http/impl/AbstractHttpRequestCreator.java
src/test/java/com/incountry/residence/sdk/StorageTest.java
src/test/java/com/incountry/residence/sdk/crypto/CustomCryptoTest.java
src/test/java/com/incountry/residence/sdk/http/mocks/FakeHttpServer.java

- [SDK-354](https://incountry.atlassian.net/browse/SDK-354)
------------
Target Release
--------------

SDK-354 [Java SDK] Release v3.3.1

---

README.md

- [SDK-336](https://incountry.atlassian.net/browse/SDK-336)
------------
Target Release
--------------

SDK-336 [Java SDK] add table of contents to README

---

gradle.properties

- [SDK-367](https://incountry.atlassian.net/browse/SDK-367)
------------
Target Release
--------------

SDK-367 [Java SDK] Release v4.0.0 - update version

---

.travis.yml
README.md
src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
src/main/java/com/incountry/residence/sdk/StorageImpl.java
src/main/java/com/incountry/residence/sdk/crypto/EncryptionSecret.java
src/main/java/com/incountry/residence/sdk/crypto/SecretsDataGenerator.java
src/test/java/com/incountry/residence/sdk/StorageTest.java
src/test/java/com/incountry/residence/sdk/crypto/CryptoProviderTest.java
src/test/java/com/incountry/residence/sdk/crypto/CustomCipherTest.java
src/test/java/com/incountry/residence/sdk/crypto/DefaultCipherTest.java
src/test/java/com/incountry/residence/sdk/crypto/SecretsTest.java
src/test/java/com/incountry/residence/sdk/crypto/testimpl/FernetCipher.java

- [SDK-367](https://incountry.atlassian.net/browse/SDK-367)
------------
Target Release
--------------

SDK-367 [Java SDK] Release v4.0.0 - unify a constructor parameter order for secrets

---

build.gradle

- [SDK-375](https://incountry.atlassian.net/browse/SDK-375)
------------
Target Release
--------------

SDK-375 [Java SDK] Update dependencies to the latest versions according to security issues - remove transitive dependencies with vulnerabilities

---

README.md
config/spotbugs/exclude.xml
src/integration/java/com/incountry/residence/sdk/OAuthTest.java
src/main/java/com/incountry/residence/sdk/StorageConfig.java
src/main/java/com/incountry/residence/sdk/StorageImpl.java
src/main/java/com/incountry/residence/sdk/tools/dao/impl/HttpDaoImpl.java
src/main/java/com/incountry/residence/sdk/tools/http/HttpExecutor.java
src/main/java/com/incountry/residence/sdk/tools/http/impl/HttpExecutorImpl.java
src/main/java/com/incountry/residence/sdk/tools/http/impl/OAuthTokenClient.java
src/main/java/com/incountry/residence/sdk/tools/http/impl/ThrottlingRequestExecutor.java
src/test/java/com/incountry/residence/sdk/HttpDaoImplTests.java
src/test/java/com/incountry/residence/sdk/ProxyUtilsTest.java
src/test/java/com/incountry/residence/sdk/StorageTest.java
src/test/java/com/incountry/residence/sdk/http/HttpExecutorImplTest.java
src/test/java/com/incountry/residence/sdk/http/TokenClientTest.java
src/test/java/com/incountry/residence/sdk/http/mocks/FakeHttpExecutor.java

- [SDK-379](https://incountry.atlassian.net/browse/SDK-379)
------------
Target Release
--------------

SDK-379 [Java SDK] Introduce throttling to http requests

---

README.md
src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
src/main/java/com/incountry/residence/sdk/StorageImpl.java
src/main/java/com/incountry/residence/sdk/tools/dao/impl/HttpDaoImpl.java
src/test/java/com/incountry/residence/sdk/HttpDaoImplTests.java
src/test/java/com/incountry/residence/sdk/StorageTest.java
src/test/java/com/incountry/residence/sdk/helper/ResponseUtils.java

- [SDK-312](https://incountry.atlassian.net/browse/SDK-312)
------------
Target Release
--------------

SDK-312 [Java SDK] write and batchWrite should return data from PoPAPI response
